language: php

cache:
  directories:
    - $COMPOSER_CACHE_DIR

php:
  - 7.1

env:
  - SYMFONY_VERSION=3.0.*

before_install:
  - composer self-update
  - composer require --no-update symfony/expression-language "$SYMFONY_VERSION"
  - composer require --no-update --dev symfony/yaml "$SYMFONY_VERSION"
  - composer require --no-update --dev symfony/routing "$SYMFONY_VERSION"
  - composer require --no-update --dev symfony/dependency-injection "$SYMFONY_VERSION"

install:
    - composer install --no-interaction --prefer-dist

script:
    - ./bin/phpunit --coverage-text --filter=JsonHalSerializerTest
