language: php

cache:
  directories:
    - $COMPOSER_CACHE_DIR

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm-nightly
    include:
        - php: hhvm-3.3
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.6
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.9
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.12
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.15
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.18
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-nightly
          sudo: required
          dist: trusty
          group: edge

env:
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update
  - composer require --no-update symfony/expression-language "$SYMFONY_VERSION"
  - composer require --no-update --dev symfony/yaml "$SYMFONY_VERSION"
  - composer require --no-update --dev symfony/routing "$SYMFONY_VERSION"
  - composer require --no-update --dev symfony/dependency-injection "$SYMFONY_VERSION"

install:
    - composer install --no-interaction --prefer-dist

script:
    - ./bin/phpunit --coverage-text
